name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.29.1

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code with lint
        run: flutter analyze

      - name: Run unit tests
        run: flutter test


